version: '3'

services:

  redis:
    image: redis:latest
    env_file:
      - ./config/redis.env
    restart: always

  rails:
    image: retropenbar/smashtheque-app:${DOCKER_TAG_RAILS}
    depends_on:
      - redis
    volumes:
      - rails_public:/rails/public
      - ./data/rails/log:/app/log
    env_file:
      - ./config/docker.env
      - ./config/rails.env
    restart: always

  sidekiq:
    depends_on:
      - redis
    image: retropenbar/smashtheque-app:${DOCKER_TAG_RAILS}
    entrypoint: ["/usr/local/bin/docker-entrypoint-sidekiq.sh"]
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - ./data/sidekiq/log:/app/log
    env_file:
      - ./config/docker.env
      - ./config/rails.env
    restart: on-failure

  redbot:
    image: phasecorex/red-discordbot
    volumes:
      - ./data/redbot:/data
    env_file:
      - ./config/docker.env
      - ./config/redbot.env
    restart: unless-stopped

  caddy:
    image: abiosoft/caddy:${DOCKER_TAG_CADDY}
    depends_on:
      - rails
    ports:
      - ${EXTERNAL_2015_PORT}:2015
      - ${EXTERNAL_443_PORT}:443
      - ${EXTERNAL_80_PORT}:80
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
      - ./data/caddy:/root/.caddy
      - rails_public:/rails/public:ro
    env_file:
      - ./config/caddy.env
    restart: always

  datadog:
    image: datadog/agent:${DOCKER_TAG_DATADOG}
    env_file:
      - ./config/datadog.env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
     - ./datadog/conf.d:/conf.d

volumes:
  rails_public:
